language: java
script: "mvn clean verify"
install: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_failure: echo "=== SUREFIRE REPORTS ===\n" && for F in fr.obeo.releng.targetplatform.tests/target/surefire-reports/*.txt; do echo $F && cat $F && echo; done
